"""Add Unit model and PDF URLs, remove Topic and Note

Revision ID: 06883672da38
Revises: dd8716f3c61c
Create Date: 2026-07-19 03:52:20.150967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06883672da38'
down_revision: Union[str, Sequence[str], None] = 'dd8716f3c61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.add_column('chapters', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.add_column('chapters', sa.Column('pdf_url', sa.String(), nullable=True))
    op.drop_constraint(op.f('chapters_subject_id_fkey'), 'chapters', type_='foreignkey')
    op.create_foreign_key(None, 'chapters', 'units', ['unit_id'], ['id'])
    op.drop_column('chapters', 'grade')
    op.drop_column('chapters', 'subject_id')
    op.drop_column('chapters', 'weightage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('weightage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chapters', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chapters', sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.create_foreign_key(op.f('chapters_subject_id_fkey'), 'chapters', 'subjects', ['subject_id'], ['id'])
    op.drop_column('chapters', 'pdf_url')
    op.drop_column('chapters', 'unit_id')
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('topics_chapter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('topics_pkey'))
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('notes_topic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notes_pkey')),
    sa.UniqueConstraint('topic_id', name=op.f('notes_topic_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    # ### end Alembic commands ###
