"""Add ondelete CASCADE to user relationships

Revision ID: 844826eb34d5
Revises: a3f31b184ec0
Create Date: 2026-07-20 04:54:24.304655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844826eb34d5'
down_revision: Union[str, Sequence[str], None] = 'a3f31b184ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tests_user_id_fkey'), 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_bookmarks_user_id_fkey'), 'user_bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'user_bookmarks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_progress_user_id_fkey'), 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_progress_user_id_fkey'), 'user_progress', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_bookmarks', type_='foreignkey')
    op.create_foreign_key(op.f('user_bookmarks_user_id_fkey'), 'user_bookmarks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(op.f('tests_user_id_fkey'), 'tests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
