"""Add grade to Chapter

Revision ID: e39bfb4e41d1
Revises: dd479934528f
Create Date: 2026-07-19 02:22:36.079192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e39bfb4e41d1'
down_revision: Union[str, Sequence[str], None] = 'dd479934528f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('grade', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'grade')
    # ### end Alembic commands ###
